Assignment05/StateManagement/Pages/Confirm.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace StateManagement.Pages
{
   using Models;
   using Utils;

   public class ConfirmModel : PageModel
   {
      [BindProperty]
      public UserInfo UInfo { get; set; }
      [TempData]
      public string TempDataWiz { get; set; }
      public string ConfirmMessage { get; set; }
      public IActionResult OnGet( )
      {
         //if( TempDataWiz != null )
         //   UInfo = JsonConvert.DeserializeObject<UserInfo>( TempDataWiz );
         //else
         //   return RedirectToPage( "WizStep1" );
         //UInfo.Wizhidden = JsonConvert.SerializeObject( UInfo );
         //UInfo = CookieFacade.UInfo;
         UInfo = SessionFacade.UInfo;
         if( UInfo == null )
         {
            return RedirectToPage( "WizStep1" );
         }

         return Page( );
      }
      public IActionResult OnPostFinishButton( )
      {
         //if( UInfo.Wizhidden != null )
         //{
         //   UInfo = JsonConvert.DeserializeObject<UserInfo>( UInfo.Wizhidden );
         //   //write to DB
         //}
         if( UInfo != null )
         {
            //CookieFacade.UInfo = this.UInfo;
            // write to DB
         }
         ConfirmMessage = "Above Info has been recorded successfully..";
         //return RedirectToAction("WizStep1");
         return RedirectToPage( "Index" );
      }
      public IActionResult OnPostPrevButton( )
      {
         //TempDataWiz = UInfo.Wizhidden;
         //CookieFacade.UInfo = UInfo;
         return RedirectToPage( "WizStep3" );
      }
   }
}

Assignment05/StateManagement/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StateManagement.Pages
{
   [ResponseCache( Duration = 0, Location = ResponseCacheLocation.None, NoStore = true )]
   public class ErrorModel : PageModel
   {
      public string RequestId { get; set; }

      public bool ShowRequestId => !string.IsNullOrEmpty( RequestId );

      private readonly ILogger<ErrorModel> _logger;

      public ErrorModel( ILogger<ErrorModel> logger )
      {
         _logger = logger;
      }

      public void OnGet( )
      {
         RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
      }
   }
}

Assignment05/StateManagement/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StateManagement.Pages
{
   using Models;
   using Utils;

   public class IndexModel : PageModel
   {
      private readonly ILogger<IndexModel> _logger;
      public Student Stu { get; set; }

      public IndexModel( ILogger<IndexModel> logger )
      {
         _logger = logger;
      }

      public void OnGet( )
      {
         //Stu = HttpContext.Session.Get< Student >( "studentinfokey" );
         Stu = SessionFacade.STU;
      }
   }
}

Assignment05/StateManagement/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StateManagement.Pages
{
   public class PrivacyModel : PageModel
   {
      private readonly ILogger<PrivacyModel> _logger;

      public PrivacyModel( ILogger<PrivacyModel> logger )
      {
         _logger = logger;
      }

      public void OnGet( )
      {
      }
   }
}

Assignment05/StateManagement/Pages/SessionTest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StateManagement.Pages
{
   using Models;
   using Utils;

   public class SessionTestModel : PageModel
   {
      public string Message { get; set; }
      public void OnGet( )
      {
         Student s1 = new Student{ FirstName = "Bill", LastName = "Baker", Id = 1234 };
         //HttpContext.Session.Set< Student >( "studentinfokey", s1 );
         SessionFacade.STU = s1;
         Message = "Student data stored successfully in session";
      }
   }
}

Assignment05/StateManagement/Pages/SetProductOnSale.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StateManagement.Pages
{
   using Services;
   using Models;
   using Utils;

   public class SetProductOnSaleModel : PageModel
   {
      IProducts _iprod = null;

      public SetProductOnSaleModel( IProducts iprod )
      {
         _iprod = iprod;
      }

      public string Message { get; set; }

      public List<Product> PList { get; set; }

      public void OnGet( )
      {
         PList = _iprod.GetProducts( );
      }

      public void OnGetSetOnSale( int prodid )
      {
         PList = _iprod.GetProducts( );
         Product pr = (from p in PList
                       where p.ProductId == prodid
                       select p).FirstOrDefault();
         if( pr != null )
         {
            //SessionFacade.PROD = pr;
            CookieFacade.PROD = pr;
            Message = pr.ProductName + " set on sale";
         }
      }
      public IActionResult OnPostClearSession( )
      {
         //HttpContextHelper.HttpCtx.Session.Clear(); // via our helper class
         //HttpContext.Session.Clear( ); // HttpContext is available to every page by default
         CookieFacade.PROD = null;
         Message = "";
         return RedirectToPage( );
      }

   }
}

Assignment05/StateManagement/Pages/ShowProductOnSale.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StateManagement.Pages
{
   using Models;
   using Utils;

   public class ShowProductOnSaleModel : PageModel
   {
      public Product Prod { get; set; }

      public void OnGet( )
      {
         //Prod = SessionFacade.PROD;
         Prod = CookieFacade.PROD;
      }
   }
}

Assignment05/StateManagement/Pages/WizStep1.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace StateManagement.Pages
{
   using Utils;
   using Models;

   public class WizStep1Model : PageModel
   {
      [BindProperty]
      public UserInfo UInfo { get; set; }
      [TempData]
      public string TempDataWiz { get; set; }
      public void OnGet( )
      {
         //if( TempDataWiz != null ) // coming back from another step
         //   UInfo = JsonConvert.DeserializeObject<UserInfo>( TempDataWiz );
         //UInfo = CookieFacade.UInfo;
         UInfo = SessionFacade.UInfo;
      }
      public IActionResult OnPost( )
      {
         //if( UInfo.Wizhidden != null )
         //{
         //   //UInfo = JsonConvert.DeserializeObject<UserInfo>( UInfo.Wizhidden );
         //}
         ModelState.Remove( "UInfo.StreetAddress" );
         ModelState.Remove( "UInfo.City" );
         ModelState.Remove( "UInfo.State" );
         ModelState.Remove( "UInfo.Telephone" );
         ModelState.Remove( "UInfo.UserPin" );
         var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new
         { x.Key, x.Value.Errors }).ToArray();
         if( ModelState.IsValid )
         {
            //UInfo.Wizhidden = "";
            //TempDataWiz = JsonConvert.SerializeObject( UInfo );
            //CookieFacade.UInfo = this.UInfo;
            SessionFacade.UInfo = this.UInfo;
            return RedirectToPage( "WizStep2" );
         }
         return Page( );
      }
   }
}

Assignment05/StateManagement/Pages/WizStep2.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace StateManagement.Pages
{
   using Models;
   using Utils;

   public class WizStep2Model : PageModel
   {
      [BindProperty]
      public UserInfo UInfo { get; set; }
      [TempData]
      public string TempDataWiz { get; set; }
      public IActionResult OnGet( )
      {
         //if( TempDataWiz != null )
         //   UInfo = JsonConvert.DeserializeObject<UserInfo>( TempDataWiz );
         //else
         //   return RedirectToPage( "WizStep1" );
         //UInfo.Wizhidden = JsonConvert.SerializeObject( UInfo );
         //UInfo = CookieFacade.UInfo;
         UInfo = SessionFacade.UInfo;
         if( UInfo == null )
         {
            return RedirectToPage( "WizStep1" );
         }
         
         return Page( );
      }
      public IActionResult OnPostNextButton( )
      {
         //UserInfo uprev = null;
         //if( UInfo.Wizhidden != null )
         //   //UInfo = JsonConvert.DeserializeObject<UserInfo>(UInfo.Wizhidden);
         //   uprev = JsonConvert.DeserializeObject<UserInfo>( UInfo.Wizhidden );
         //else
         //   return RedirectToPage( "WizStep1" );
         //UserInfo uprev = CookieFacade.UInfo;
         UserInfo uprev = SessionFacade.UInfo;
         //if( CookieFacade.UInfo == null )
         if( SessionFacade.UInfo == null )
         {
            return RedirectToPage( "WizStep1" );
         }
         ModelState.Remove( "UInfo.FirstName" );
         ModelState.Remove( "UInfo.LastName" );
         ModelState.Remove( "UInfo.Email" );
         ModelState.Remove( "UInfo.Cellphone" );
         ModelState.Remove( "UInfo.Telephone" );
         ModelState.Remove( "UInfo.UserPin" );
         var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new
         { x.Key, x.Value.Errors }).ToArray();
         if( ModelState.IsValid )
         {
            UInfo.FirstName = uprev.FirstName;
            UInfo.LastName = uprev.LastName;
            UInfo.Email = uprev.Email;
            //UInfo.Wizhidden = "";
            //TempDataWiz = JsonConvert.SerializeObject( UInfo );
            //CookieFacade.UInfo = this.UInfo;
            SessionFacade.UInfo = this.UInfo;
            return RedirectToPage( "WizStep3" );
         }
         return Page( );
      }
      public IActionResult OnPostPrevButton( )
      {
         //if( UInfo.Wizhidden != null )
         //   UInfo = JsonConvert.DeserializeObject<UserInfo>( UInfo.Wizhidden );
         //else
         //   return RedirectToPage( "WizStep1" );
         //UInfo.Wizhidden = "";
         //TempDataWiz = JsonConvert.SerializeObject( UInfo );
         return RedirectToPage( "WizStep1" );
      }
   }
}

Assignment05/StateManagement/Pages/WizStep3.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace StateManagement.Pages
{
   using Models;
   using Utils;

   public class WizStep3Model : PageModel
   {
      [BindProperty]
      public UserInfo UInfo { get; set; }
      [TempData]
      public string TempDataWiz { get; set; }
      public IActionResult OnGet( )
      {
         //if( TempDataWiz != null )
         //   UInfo = JsonConvert.DeserializeObject<UserInfo>( TempDataWiz );
         //else
         //   return RedirectToPage( "WizStep1" );
         //UInfo.Wizhidden = JsonConvert.SerializeObject( UInfo );
         //UInfo = CookieFacade.UInfo;
         UInfo = SessionFacade.UInfo;
         if( UInfo == null )
         {
            return RedirectToPage( "WizStep1" );
         }

         return Page( );
      }
      public IActionResult OnPostNextButton( )
      {
         //UserInfo uprev = null;
         //if( UInfo.Wizhidden != null )
         //   //UInfo = JsonConvert.DeserializeObject<UserInfo>(UInfo.Wizhidden);
         //   uprev = JsonConvert.DeserializeObject<UserInfo>( UInfo.Wizhidden );
         //else
         //   return RedirectToPage( "WizStep1" );
         //UserInfo uprev = CookieFacade.UInfo;
         UserInfo uprev = SessionFacade.UInfo;
         //if( CookieFacade.UInfo == null )
         if( SessionFacade.UInfo == null )
         {
            return RedirectToPage( "WizStep1" );
         }
         ModelState.Remove( "UInfo.FirstName" );
         ModelState.Remove( "UInfo.LastName" );
         ModelState.Remove( "UInfo.Email" );
         ModelState.Remove( "UInfo.StreetAddress" );
         ModelState.Remove( "UInfo.City" );
         ModelState.Remove( "UInfo.State" );
         var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new
         { x.Key, x.Value.Errors }).ToArray();
         if( ModelState.IsValid )
         {
            UInfo.FirstName = uprev.FirstName;
            UInfo.LastName = uprev.LastName;
            UInfo.Email = uprev.Email;
            UInfo.State = uprev.State;
            UInfo.StreetAddress = uprev.StreetAddress;
            UInfo.City = uprev.City;
            //UInfo.Wizhidden = "";
            //TempDataWiz = JsonConvert.SerializeObject( UInfo );
            //CookieFacade.UInfo = this.UInfo;
            SessionFacade.UInfo = this.UInfo;
            return RedirectToPage( "Confirm" );
         }
         return Page( );
      }
      public IActionResult OnPostPrevButton( )
      {
         //if( UInfo.Wizhidden != null )
         //   UInfo = JsonConvert.DeserializeObject<UserInfo>( UInfo.Wizhidden );
         //else
         //   return RedirectToPage( "WizStep1" );
         //UInfo.Wizhidden = "";
         //TempDataWiz = JsonConvert.SerializeObject( UInfo );
         return RedirectToPage( "WizStep2" );
      }
   }
}

Assignment05/StateManagement/Pages/Confirm.cshtml
@page
@model StateManagement.Pages.ConfirmModel
@{
   ViewData[ "Title" ] = "Confirm";
}22
<h1>Confirm</h1>
<div>
   <h4>UserInfo</h4>
   <hr />
   <dl class="row">
      <dt class="col-sm-2">
         @Html.DisplayNameFor( model => model.UInfo.FirstName )
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor( model => model.UInfo.FirstName )
      </dd>
      <dt class="col-sm-2">
         @Html.DisplayNameFor( model => model.UInfo.LastName )
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor( model => model.UInfo.LastName )
      </dd>
      <dt class="col-sm-2">
         @Html.DisplayNameFor( model => model.UInfo.Email )
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor( model => model.UInfo.Email )
      </dd>
      <dt class="col-sm-2">
         @Html.DisplayNameFor( model => model.UInfo.StreetAddress )
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor( model => model.UInfo.StreetAddress )
      </dd>
      <dt class="col-sm-2">
         @Html.DisplayNameFor( model => model.UInfo.City )
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor( model => model.UInfo.City )
      </dd>
      <dt class="col-sm-2">
         @Html.DisplayNameFor( model => model.UInfo.State )
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor( model => model.UInfo.State )
      </dd>
      <dt class="col-sm-2">
         @Html.DisplayNameFor( model => model.UInfo.Telephone )
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor( model => model.UInfo.Telephone )
      </dd>
      <dt class="col-sm-2">
         @Html.DisplayNameFor( model => model.UInfo.CellPhone )
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor( model => model.UInfo.CellPhone )
      </dd>
      <dt class="col-sm-2">
         @Html.DisplayNameFor( model => model.UInfo.UserPin )
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor( model => model.UInfo.UserPin )
      </dd>
   </dl>
</div>
<form asp-action="Confirm">
   <div class="form-group">
      <input type="hidden" asp-for="UInfo.Wizhidden" class="form-control" />
      <input type="submit" value="Prev" asp-page-handler="prevButton" name="prevButton"
             class="btn btn-primary" />
      <input type="submit" value="Finish" asp-page-handler="finishButton"
             name="finishButton" class="btn btn-primary" />
   </div>
</form>

Assignment05/StateManagement/Pages/Index.cshtml
@page
@model IndexModel
@{
   ViewData[ "Title" ] = "Home page";
}

<div class="text-center">
   <h1 class="display-4">Welcome</h1>
   <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
@if( Model.Stu != null )
{
   <h2>Student stoed in Session</h2>
   <div>@Model.Stu.FirstName</div>
   <div>@Model.Stu.LastName</div>
   <div>@Model.Stu.Id</div>
}
else
{
   <p>No Student stored in Session</p>
}

Assignment05/StateManagement/Pages/SessionTest.cshtml
@page
@model StateManagement.Pages.SessionTestModel
@{
   ViewData[ "Title" ] = "SessionTest";
}
<h1>Session Test</h1>
<div>@Model.Message</div>

Assignment05/StateManagement/Pages/SetProductOnSale.cshtml
@page
@model StateManagement.Pages.SetProductOnSaleModel
@{
   ViewData[ "Title" ] = "SetProductOnSale";
}
<h1>Set Product On Sale</h1>
<table class="table">
   <tr><th>ProductId</th><th>ProductName</th><th>Price</th><th>Set OnSale</th></tr>
   @foreach( var pr in Model.PList )
   {
      <tr>
         <td>@pr.ProductId</td>
         <td>@pr.ProductName</td>
         <td>@pr.Price</td>
         <td>
            <a asp-page-handler="SetOnSale" asp-route-prodid="@pr.ProductId">SetOnSale</a>
         </td>
      </tr>
   }
</table>
<form method="post">
   <button class="btn-success" asp-page-handler="ClearSession">Clear Session</button>
</form>
<div style="color:red">@Model.Message</div>

Assignment05/StateManagement/Pages/ShowProductOnSale.cshtml
@page
@model StateManagement.Pages.ShowProductOnSaleModel
@{
   ViewData[ "Title" ] = "ShowProductOnSale";
}
<h1>Product On Sale</h1>
@if( Model.Prod != null )
{
   @Model.Prod.ProductId
   <br />
   @Model.Prod.ProductName
   <br />
   @Model.Prod.Price
}
else
{
   @: No Product on Sale
}

Assignment05/StateManagement/Pages/WizStep1.cshtml
@page
@model StateManagement.Pages.WizStep1Model
@{
   ViewData[ "Title" ] = "WizStep1";
}
<h1>WizStep1</h1>
<h4>UserInfo</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="WizStep1">
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         <div class="form-group">
            <label asp-for="UInfo.FirstName" class="control-label"></label>
            <input asp-for="UInfo.FirstName" class="form-control" />
            <span asp-validation-for="UInfo.FirstName" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="UInfo.LastName" class="control-label"></label>
            <input asp-for="UInfo.LastName" class="form-control" />
            <span asp-validation-for="UInfo.LastName" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="UInfo.Email" class="control-label"></label>
            <input asp-for="UInfo.Email" class="form-control" />
            <span asp-validation-for="UInfo.Email" class="text-danger"></span>
         </div>
         <div class="form-group">
            <input type="submit" value="Next" class="btn btn-primary" />
            <input type="hidden" asp-for="UInfo.Wizhidden" />
         </div>
      </form>
   </div>
</div>
<div>
   <a asp-page="Index">Back to Home</a>
</div>

Assignment05/StateManagement/Pages/WizStep2.cshtml
@page
@model StateManagement.Pages.WizStep2Model
@{
   ViewData[ "Title" ] = "WizStep2";
}
<h1>WizStep2</h1>
<h4>UserInfo</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="WizStep2">
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         <div class="form-group">
            <label asp-for="UInfo.StreetAddress" class="control-label"></label>
            <input asp-for="UInfo.StreetAddress" class="form-control" />
            <span asp-validation-for="UInfo.StreetAddress" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="UInfo.City" class="control-label"></label>
            <input asp-for="UInfo.City" class="form-control" />
            <span asp-validation-for="UInfo.City" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="UInfo.State" class="control-label"></label>
            <input asp-for="UInfo.State" class="form-control" />
            <span asp-validation-for="UInfo.State" class="text-danger"></span>
         </div>
         <div class="form-group">
            <input type="hidden" asp-for="UInfo.Wizhidden" class="form-control" />
            <input type="submit" formnovalidate value="Prev" asp-page-handler="prevButton" name="prevButton" class="btn btn-primary" />
            <input type="submit" value="Next" name="nextButton" asp-page-handler="nextButton" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>

Assignment05/StateManagement/Pages/WizStep3.cshtml
@page
@model StateManagement.Pages.WizStep3Model
@{
   ViewData[ "Title" ] = "WizStep3";
}
<h1>WizStep3</h1>
<h4>UserInfo</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="WizStep3">
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         <div class="form-group">
            <label asp-for="UInfo.Telephone" class="control-label"></label>
            <input asp-for="UInfo.Telephone" class="form-control" />
            <span asp-validation-for="UInfo.Telephone" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="UInfo.CellPhone" class="control-label"></label>
            <input asp-for="UInfo.CellPhone" class="form-control" />
            <span asp-validation-for="UInfo.CellPhone" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="UInfo.UserPin" class="control-label"></label>
            <input asp-for="UInfo.UserPin" class="form-control" />
            <span asp-validation-for="UInfo.UserPin" class="text-danger"></span>
         </div>
         <div class="form-group">
            <input type="hidden" asp-for="UInfo.Wizhidden" class="form-control" />
            <input type="submit" formnovalidate value="Prev" asp-page-handler="prevButton" name="prevButton" class="btn btn-primary" />
            <input type="submit" value="Next" name="nextButton" asp-page-handler="nextButton" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>